# Generated by Django 3.2.6 on 2021-12-13 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_bookservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
