# Generated by Django 3.2.6 on 2021-12-14 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_bookservice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='complaint',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
