# Generated by Django 3.2.6 on 2021-12-14 07:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_bookservice_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookservice',
            name='price',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.bookservice')),
            ],
        ),
    ]
