# Generated by Django 3.2.6 on 2021-12-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20211214_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
