# Generated by Django 3.2.6 on 2021-12-14 06:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_alter_order_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Item',
        ),
    ]
